// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: soul_sifter.proto

#ifndef RPCZ_soul_5fsifter_2eproto__INCLUDED
#define RPCZ_soul_5fsifter_2eproto__INCLUDED

#include <string>
#include <rpcz/service.hpp>

namespace google {
namespace protobuf {
class ServiceDescriptor;
class MethodDescriptor;
}  // namespace protobuf
}  // namespace google
namespace rpcz {
class rpc;
class closure;
class rpc_channel;
}  //namesacpe rpcz
#include "soul_sifter.pb.h"
void rpcz_protobuf_AssignDesc_soul_5fsifter_2eproto();
void rpcz_protobuf_ShutdownFile_soul_5fsifter_2eproto();

#endif  // RPCZ_soul_5fsifter_2eproto__INCLUDED
