// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "soul_sifter.rpcz.h"
#include "soul_sifter.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/stubs/once.h>
#include <rpcz/rpcz.hpp>
namespace {
}  // anonymouse namespace

void rpcz_protobuf_AssignDesc_soul_5fsifter_2eproto() {
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "soul_sifter.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &rpcz_protobuf_AssignDesc_soul_5fsifter_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void rpcz_protobuf_ShutdownFile_soul_5fsifter_2eproto() {
}

void rpcz_protobuf_AddDesc_soul_5fsifter_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021soul_sifter.proto\"8\n\005Genre\022\n\n\002id\030\001 \001(\005"
    "\022\014\n\004name\030\002 \001(\t\022\025\n\005child\030\003 \003(\0132\006.Genre", 77);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "soul_sifter.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&rpcz_protobuf_ShutdownFile_soul_5fsifter_2eproto);
}
