// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: soul_sifter_service.proto

#ifndef PROTOBUF_soul_5fsifter_5fservice_2eproto__INCLUDED
#define PROTOBUF_soul_5fsifter_5fservice_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace dogatech {
namespace soulsifter {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_soul_5fsifter_5fservice_2eproto();
void protobuf_AssignDesc_soul_5fsifter_5fservice_2eproto();
void protobuf_ShutdownFile_soul_5fsifter_5fservice_2eproto();

class GetSongRequest;
class GetSongResponse;

// ===================================================================

class GetSongRequest : public ::google::protobuf::Message {
 public:
  GetSongRequest();
  virtual ~GetSongRequest();

  GetSongRequest(const GetSongRequest& from);

  inline GetSongRequest& operator=(const GetSongRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSongRequest& default_instance();

  void Swap(GetSongRequest* other);

  // implements Message ----------------------------------------------

  GetSongRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetSongRequest& from);
  void MergeFrom(const GetSongRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dogatech.soulsifter.GetSongRequest)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_soul_5fsifter_5fservice_2eproto();
  friend void protobuf_AssignDesc_soul_5fsifter_5fservice_2eproto();
  friend void protobuf_ShutdownFile_soul_5fsifter_5fservice_2eproto();

  void InitAsDefaultInstance();
  static GetSongRequest* default_instance_;
};
// -------------------------------------------------------------------

class GetSongResponse : public ::google::protobuf::Message {
 public:
  GetSongResponse();
  virtual ~GetSongResponse();

  GetSongResponse(const GetSongResponse& from);

  inline GetSongResponse& operator=(const GetSongResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSongResponse& default_instance();

  void Swap(GetSongResponse* other);

  // implements Message ----------------------------------------------

  GetSongResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetSongResponse& from);
  void MergeFrom(const GetSongResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string title = 1;
  inline bool has_title() const;
  inline void clear_title();
  static const int kTitleFieldNumber = 1;
  inline const ::std::string& title() const;
  inline void set_title(const ::std::string& value);
  inline void set_title(const char* value);
  inline void set_title(const char* value, size_t size);
  inline ::std::string* mutable_title();
  inline ::std::string* release_title();
  inline void set_allocated_title(::std::string* title);

  // @@protoc_insertion_point(class_scope:dogatech.soulsifter.GetSongResponse)
 private:
  inline void set_has_title();
  inline void clear_has_title();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* title_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_soul_5fsifter_5fservice_2eproto();
  friend void protobuf_AssignDesc_soul_5fsifter_5fservice_2eproto();
  friend void protobuf_ShutdownFile_soul_5fsifter_5fservice_2eproto();

  void InitAsDefaultInstance();
  static GetSongResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// GetSongRequest

// optional int32 id = 1;
inline bool GetSongRequest::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetSongRequest::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetSongRequest::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetSongRequest::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 GetSongRequest::id() const {
  return id_;
}
inline void GetSongRequest::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// GetSongResponse

// optional string title = 1;
inline bool GetSongResponse::has_title() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetSongResponse::set_has_title() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetSongResponse::clear_has_title() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetSongResponse::clear_title() {
  if (title_ != &::google::protobuf::internal::kEmptyString) {
    title_->clear();
  }
  clear_has_title();
}
inline const ::std::string& GetSongResponse::title() const {
  return *title_;
}
inline void GetSongResponse::set_title(const ::std::string& value) {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  title_->assign(value);
}
inline void GetSongResponse::set_title(const char* value) {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  title_->assign(value);
}
inline void GetSongResponse::set_title(const char* value, size_t size) {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  title_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* GetSongResponse::mutable_title() {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  return title_;
}
inline ::std::string* GetSongResponse::release_title() {
  clear_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = title_;
    title_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void GetSongResponse::set_allocated_title(::std::string* title) {
  if (title_ != &::google::protobuf::internal::kEmptyString) {
    delete title_;
  }
  if (title) {
    set_has_title();
    title_ = title;
  } else {
    clear_has_title();
    title_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace soulsifter
}  // namespace dogatech

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_soul_5fsifter_5fservice_2eproto__INCLUDED
