//
//  Style.cpp
//  soul-sifter
//
//  Created by Robby Neale
//  Generated by generate_model.rb
//

#include "Style.h"

#include <string>

#include <cppconn/connection.h>
#include <cppconn/statement.h>
#include <cppconn/prepared_statement.h>
#include <cppconn/resultset.h>
#include <cppconn/exception.h>
#include <cppconn/warning.h>

#include "MysqlAccess.h"
#include "DTVectorUtil.h"

using namespace std;

namespace soulsifter {

# pragma mark initialization

    Style::Style() :
    id(0),
    name(),
    reId(0),
    reLabel(),
    children(),
    childrenIds(),
    parents(),
    parentsIds() {
    }

    Style::Style(const Style& style) :
    id(style.getId()),
    name(style.getName()),
    reId(style.getREId()),
    reLabel(style.getRELabel()),
    children(),
    childrenIds(style.childrenIds),
    parents(),
    parentsIds(style.parentsIds) {
    }

    void Style::operator=(const Style& style) {
        id = style.getId();
        name = style.getName();
        reId = style.getREId();
        reLabel = style.getRELabel();
        childrenIds = style.childrenIds;
        parentsIds = style.parentsIds;
    }

    Style::~Style() {
        while (!children.empty()) delete children.back(), children.pop_back();
        while (!parents.empty()) delete parents.back(), parents.pop_back();
    }

    void Style::clear() {
        id = 0;
        name.clear();
        reId = 0;
        reLabel.clear();
        for (vector<Style*>::iterator it = children.begin(); it != children.end(); ++it) {
            delete *it;
        }
        children.clear();
        childrenIds.clear();
        for (vector<Style*>::iterator it = parents.begin(); it != parents.end(); ++it) {
            delete *it;
        }
        parents.clear();
        parentsIds.clear();
    }

# pragma mark static methods

    void Style::populateFields(const sql::ResultSet* rs, Style* style) {
        style->setId(rs->getInt("id"));
        style->setName(rs->getString("name"));
        style->setREId(rs->getInt("reId"));
        style->setRELabel(rs->getString("reLabel"));
        populateChildrenIds(style);
        populateParentsIds(style);
    }

    void Style::populateChildrenIds(Style* style) {
        sql::PreparedStatement *ps = MysqlAccess::getInstance().getPreparedStatement("select childId from StyleChildren where parentId = ?");
        ps->setInt(1, style->getId());
        sql::ResultSet *rs = ps->executeQuery();
        while (rs->next()) {
            style->childrenIds.push_back(rs->getInt(1));
        }
        rs->close();
        delete rs;
    }

    void Style::populateParentsIds(Style* style) {
        sql::PreparedStatement *ps = MysqlAccess::getInstance().getPreparedStatement("select parentId from StyleChildren where childId = ?");
        ps->setInt(1, style->getId());
        sql::ResultSet *rs = ps->executeQuery();
        while (rs->next()) {
            style->parentsIds.push_back(rs->getInt(1));
        }
        rs->close();
        delete rs;
    }

    Style* Style::findById(int id) {
        sql::PreparedStatement *ps = MysqlAccess::getInstance().getPreparedStatement("select * from Styles where id = ?");
        ps->setInt(1, id);
        sql::ResultSet *rs = ps->executeQuery();
        Style *style = NULL;
        if (rs->next()) {
            style = new Style();
            populateFields(rs, style);
        }
        rs->close();
        delete rs;

        return style;
    }

    Style* Style::findByREId(int reId) {
        sql::PreparedStatement *ps = MysqlAccess::getInstance().getPreparedStatement("select * from Styles where reId = ?");
        ps->setInt(1, reId);
        sql::ResultSet *rs = ps->executeQuery();
        Style *style = NULL;
        if (rs->next()) {
            style = new Style();
            populateFields(rs, style);
        }
        rs->close();
        delete rs;

        return style;
    }

# pragma mark persistence

    bool Style::sync() {
        Style* style = findById(id);
        if (!style) {
            return true;
        }

        // check fields
        bool needsUpdate = false;
        if (id != style->getId()) {
            if (id) {
                cout << "updating style's id from " << style->getId() << " to " << id << endl;
                needsUpdate = true;
            } else {
                id = style->getId();
            }
        }
        if (name.compare(style->getName())) {
            if (!name.empty()) {
                cout << "updating style name from " << style->getName() << " to " << name << endl;
                needsUpdate = true;
            } else {
                name = style->getName();
            }
        }
        if (reId != style->getREId()) {
            if (reId) {
                cout << "updating style's reId from " << style->getREId() << " to " << reId << endl;
                needsUpdate = true;
            } else {
                reId = style->getREId();
            }
        }
        if (reLabel.compare(style->getRELabel())) {
            if (!reLabel.empty()) {
                cout << "updating style reLabel from " << style->getRELabel() << " to " << reLabel << endl;
                needsUpdate = true;
            } else {
                reLabel = style->getRELabel();
            }
        }
        if (!dogatech::equivalentVectors<int>(childrenIds, style->childrenIds)) {
            if (!dogatech::containsVector<int>(childrenIds, style->childrenIds)) {
                cout << "updating style childrenIds" << endl;
                needsUpdate = true;
            }
            dogatech::appendUniqueVector<int>(style->childrenIds, &childrenIds);
            children.clear();
        }
        if (!dogatech::equivalentVectors<int>(parentsIds, style->parentsIds)) {
            if (!dogatech::containsVector<int>(parentsIds, style->parentsIds)) {
                cout << "updating style parentsIds" << endl;
                needsUpdate = true;
            }
            dogatech::appendUniqueVector<int>(style->parentsIds, &parentsIds);
            parents.clear();
        }
        return needsUpdate;
    }

    int Style::update() {
        try {
            sql::PreparedStatement *ps = MysqlAccess::getInstance().getPreparedStatement("update Styles set name=?, reId=?, reLabel=? where id=?");
            ps->setString(1, name);
            ps->setInt(2, reId);
            ps->setString(3, reLabel);
            ps->setInt(4, id);
            int result = ps->executeUpdate();
            if (!childrenIds.empty()) {
                ps = MysqlAccess::getInstance().getPreparedStatement("insert ignore into StyleChildren (parentId, childId) values (?, ?)");
                for (vector<int>::const_iterator it = childrenIds.begin(); it != childrenIds.end(); ++it) {
                    ps->setInt(1, id);
                    ps->setInt(2, *it);
                    ps->executeUpdate();
                }
            }
            if (!parentsIds.empty()) {
                ps = MysqlAccess::getInstance().getPreparedStatement("insert ignore into StyleChildren (childId, parentId) values (?, ?)");
                for (vector<int>::const_iterator it = parentsIds.begin(); it != parentsIds.end(); ++it) {
                    ps->setInt(1, id);
                    ps->setInt(2, *it);
                    ps->executeUpdate();
                }
            }
            return result;
        } catch (sql::SQLException &e) {
            cerr << "ERROR: SQLException in " << __FILE__;
            cerr << " (" << __func__<< ") on line " << __LINE__ << endl;
            cerr << "ERROR: " << e.what();
            cerr << " (MySQL error code: " << e.getErrorCode();
            cerr << ", SQLState: " << e.getSQLState() << ")" << endl;
            return 0;
        }
    }

    int Style::save() {
        try {
            sql::PreparedStatement *ps = MysqlAccess::getInstance().getPreparedStatement("insert into Styles (name, reId, reLabel) values (?, ?, ?)");
            ps->setString(1, name);
            ps->setInt(2, reId);
            ps->setString(3, reLabel);
            int saved = ps->executeUpdate();
            if (!saved) {
                cerr << "Not able to save style" << endl;
                return saved;
            } else {
                const int id = MysqlAccess::getInstance().getLastInsertId();
                if (id == 0) {
                    cerr << "Inserted style, but unable to retreive inserted ID." << endl;
                    return saved;
                }
                ps = MysqlAccess::getInstance().getPreparedStatement("insert ignore into StyleChildren (styleId, childId) values (?, ?)");
                for (vector<int>::iterator it = childrenIds.begin(); it != childrenIds.end(); ++it) {
                    ps->setInt(1, id);
                    ps->setInt(2, *it);
                    if (!ps->executeUpdate()) {
                        cerr << "Did not save child for style " << id << endl;
                    }
                }
                ps = MysqlAccess::getInstance().getPreparedStatement("insert ignore into StyleParents (styleId, parentId) values (?, ?)");
                for (vector<int>::iterator it = parentsIds.begin(); it != parentsIds.end(); ++it) {
                    ps->setInt(1, id);
                    ps->setInt(2, *it);
                    if (!ps->executeUpdate()) {
                        cerr << "Did not save parent for style " << id << endl;
                    }
                }
                return saved;
            }
        } catch (sql::SQLException &e) {
            cerr << "ERROR: SQLException in " << __FILE__;
            cerr << " (" << __func__<< ") on line " << __LINE__ << endl;
            cerr << "ERROR: " << e.what();
            cerr << " (MySQL error code: " << e.getErrorCode();
            cerr << ", SQLState: " << e.getSQLState() << ")" << endl;
            return 0;
        }
    }


# pragma mark accessors

    const int Style::getId() const { return id; }
    void Style::setId(const int id) { this->id = id; }

    const string& Style::getName() const { return name; }
    void Style::setName(const string& name) { this->name = name; }

    const int Style::getREId() const { return reId; }
    void Style::setREId(const int reId) { this->reId = reId; }

    const string& Style::getRELabel() const { return reLabel; }
    void Style::setRELabel(const string& reLabel) { this->reLabel = reLabel; }

    const vector<Style*>& Style::getChildren() {
        if (children.empty() && !childrenIds.empty()) {
            for (vector<int>::const_iterator it = childrenIds.begin(); it != childrenIds.end(); ++it) {
                children.push_back(Style::findById(*it));
            }
        }
        return children;
    }
    void Style::setChildren(const vector<Style*>& children) { this->children = children; }
    void Style::addChild(const Style& child) { children.push_back(new Style(child)); }
    void Style::removeChild(int childId) {
        for (vector<Style*>::iterator it = children.begin(); it != children.end(); ++it) {
            if (childId == (*it)->getId()) {
                children.erase(it);
            }
        }
    }

    const vector<Style*>& Style::getParents() {
        if (parents.empty() && !parentsIds.empty()) {
            for (vector<int>::const_iterator it = parentsIds.begin(); it != parentsIds.end(); ++it) {
                parents.push_back(Style::findById(*it));
            }
        }
        return parents;
    }
    void Style::setParents(const vector<Style*>& parents) { this->parents = parents; }
    void Style::addParent(const Style& parent) { parents.push_back(new Style(parent)); }
    void Style::removeParent(int parentId) {
        for (vector<Style*>::iterator it = parents.begin(); it != parents.end(); ++it) {
            if (parentId == (*it)->getId()) {
                parents.erase(it);
            }
        }
    }

}
